### ISSUE TITLE
Clearing traces doesn't work in 0.1.2

### ISSUE THREAD

**Issue by CtrlSpice** [CtrlSpice/otel-desktop-viewer#125] opened 2023-05-15 23:17 UTC

**Comment by codeboten** [comment] 2023-05-22 21:43
This appears fixed in main? Or at least i can clear traces when building the latest code.

**Comment by jmorrell** [comment] 2023-05-23 18:32
We couldn't reproduce this again. Let's close this and see if it happens again.

**Closed by jmorrell** 2023-05-23 18:32 UTC
